# Base image
FROM node:16

# Working directory
WORKDIR /app

# Dependencies copy karo
COPY package*.json ./

# Install karo dependencies
RUN npm install

# App source code copy karo
COPY . .

# Build karo React app
RUN npm run build

# Serve karo build folder with serve package
RUN npm install -g serve

# Default command
CMD ["serve", "-s", "build", "-l", "3000"]

# Expose port 3000
EXPOSE 3000
